[[redirects]]
  from = "/api/*"
  to = "https://script.google.com/macros/s/AKfycbzEjKnyPdMddDS35Tt_scPMU-Urs7byM8vaRIfJrYK8lTgLqIkfv2HJyveqSfHPhbv8/exec/:splat"
  status = 200
  force = true



[[redirects]]
  from = "/api/get/*"
  to = "https://script.google.com/macros/s/AKfycbzK6lE9fWk1wfigErAimTOtzd6ALUomnB3mB8vj0NZhosovWKfLTIRE02Y8Q8F6-UPZ/exec/:splat"
  status = 200
  force = true



[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
